import io
import json
import re
import zipfile
from collections import defaultdict, deque
from uuid import UUID

from app.models import GraphEdge, GraphNode, Project
from app.services.storage import get_storage

POSITION_MAP = {
    "left": "left",
    "center": "center",
    "right": "right",
}


def _sanitize_renpy_name(name: str) -> str:
    cleaned = re.sub(r"[^a-zA-Z0-9_]", "_", name.strip())
    if not cleaned or cleaned[0].isdigit():
        cleaned = f"n_{cleaned}"
    return cleaned.lower()


def validate_graph(project: Project) -> list[str]:
    errors: list[str] = []
    nodes = project.nodes
    edges = project.edges

    start_nodes = [n for n in nodes if n.type == "start"]
    loading_nodes = [n for n in nodes if n.type == "loading"]
    main_menu_nodes = [n for n in nodes if n.type == "main_menu"]

    if len(loading_nodes) != 1:
        errors.append("Graph must have exactly one 'loading' node")
    if len(main_menu_nodes) != 1:
        errors.append("Graph must have exactly one 'main_menu' node")
    if len(start_nodes) == 0:
        errors.append("Graph must have exactly one 'start' node")
    elif len(start_nodes) > 1:
        errors.append("Graph must have only one 'start' node")

    labels = [n.label for n in nodes if n.label]
    if len(labels) != len(set(labels)):
        errors.append("All node labels must be unique")

    adj: dict[UUID, list[GraphEdge]] = defaultdict(list)
    for edge in edges:
        adj[edge.source_node_id].append(edge)

    if loading_nodes:
        visited: set[UUID] = set()
        queue: deque[UUID] = deque([loading_nodes[0].id])
    elif start_nodes:
        visited: set[UUID] = set()
        queue: deque[UUID] = deque([start_nodes[0].id])
    else:
        visited = set()
        queue = deque()

    if queue:
        while queue:
            current = queue.popleft()
            if current in visited:
                continue
            visited.add(current)
            for edge in adj[current]:
                queue.append(edge.target_node_id)

        unreachable = [n.label for n in nodes if n.id not in visited]
        if unreachable:
            errors.append(f"Unreachable nodes from entry: {', '.join(unreachable)}")

    for node in nodes:
        if node.type in {"condition", "choice"}:
            outgoing = adj.get(node.id, [])
            if not outgoing:
                errors.append(f"Node '{node.label}' must have outgoing connections")

    return errors


def _build_adjacency(edges: list[GraphEdge]) -> dict[UUID, list[GraphEdge]]:
    adj: dict[UUID, list[GraphEdge]] = defaultdict(list)
    for edge in edges:
        adj[edge.source_node_id].append(edge)
    return adj


def _get_next_linear(
    node_id: UUID,
    adj: dict[UUID, list[GraphEdge]],
    skip_handles: set[str | None] | None = None,
) -> UUID | None:
    skip_handles = skip_handles or set()
    outgoing = [e for e in adj.get(node_id, []) if e.source_handle not in skip_handles]
    if len(outgoing) == 1:
        return outgoing[0].target_node_id
    default_edges = [e for e in outgoing if e.source_handle in (None, "default", "")]
    if len(default_edges) == 1:
        return default_edges[0].target_node_id
    return None


def _escape_renpy_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


class RenPyGenerator:
    def __init__(self, project: Project) -> None:
        self.project = project
        self.nodes_by_id = {n.id: n for n in project.nodes}
        self.assets_by_id = {str(a.id): a for a in project.assets}
        self.adj = _build_adjacency(project.edges)
        self.lines: list[str] = []
        self.visited: set[UUID] = set()
        self.storage = get_storage()

    def generate_script(self) -> str:
        self.lines = []
        self._emit_header()
        self._emit_image_definitions()

        start = next(n for n in self.project.nodes if n.type == "start")
        self.lines.append("")
        self.lines.append("label start:")
        self._emit_from_node(start.id, indent=1, stop_at_branch=True)

        for node in self.project.nodes:
            if node.id in self.visited or node.type == "start":
                continue
            if node.type == "label":
                self.lines.append("")
                self.lines.append(f"label {_sanitize_renpy_name(node.label)}:")
                self._emit_from_node(node.id, indent=1, stop_at_branch=True)

        return "\n".join(self.lines) + "\n"

    def _emit_header(self) -> None:
        characters = self.project.metadata_.get("characters", [])
        self.lines.append("# Generated by Less Game Editor")
        self.lines.append("")
        for char in characters:
            name = _sanitize_renpy_name(char.get("id", "character"))
            display = char.get("display_name", name)
            color = char.get("color", "#c8ffc8")
            self.lines.append(f'define {name} = Character("{_escape_renpy_string(display)}", color="{color}")')

    def _emit_image_definitions(self) -> None:
        self.lines.append("")
        for asset in self.project.assets:
            if asset.kind in {"background", "character"}:
                safe_name = _sanitize_renpy_name(asset.filename.rsplit(".", 1)[0])
                folder = "images/bg" if asset.kind == "background" else "images/char"
                self.lines.append(f'image {safe_name} = "{folder}/{asset.filename}"')

    def _indent(self, level: int, text: str) -> None:
        self.lines.append("    " * level + text)

    def _emit_from_node(
        self,
        node_id: UUID,
        indent: int,
        stop_at_branch: bool = False,
    ) -> None:
        current_id: UUID | None = node_id
        while current_id and current_id not in self.visited:
            node = self.nodes_by_id[current_id]
            self.visited.add(current_id)

            if node.type == "start":
                self._emit_start(node, indent)
            elif node.type in {"loading", "main_menu", "settings"}:
                pass
            elif node.type == "scene":
                self._emit_scene(node, indent)
            elif node.type == "dialogue":
                self._emit_dialogue(node, indent)
            elif node.type == "show_character":
                self._emit_show_character(node, indent)
            elif node.type == "hide_character":
                self._emit_hide_character(node, indent)
            elif node.type == "music":
                self._emit_music(node, indent)
            elif node.type == "sound":
                self._emit_sound(node, indent)
            elif node.type == "effect":
                self._emit_effect(node, indent)
            elif node.type == "set_variable":
                self._emit_set_variable(node, indent)
            elif node.type == "jump":
                self._emit_jump(node, indent)
                return
            elif node.type == "end":
                self._indent(indent, "return")
                return
            elif node.type == "choice":
                self._emit_choice(node, indent)
                return
            elif node.type == "condition":
                self._emit_condition(node, indent)
                return
            elif node.type == "label":
                pass

            if stop_at_branch and node.type in {"choice", "condition", "jump", "end"}:
                return

            current_id = _get_next_linear(current_id, self.adj)

    def _asset_image_name(self, asset_id: str | None) -> str | None:
        if not asset_id or asset_id not in self.assets_by_id:
            return None
        asset = self.assets_by_id[asset_id]
        return _sanitize_renpy_name(asset.filename.rsplit(".", 1)[0])

    def _emit_start(self, node: GraphNode, indent: int) -> None:
        data = node.data or {}
        image_name = self._asset_image_name(data.get("background_asset_id"))
        if image_name:
            self._indent(indent, f"scene {image_name}")
        music_id = data.get("music_asset_id")
        if music_id and str(music_id) in self.assets_by_id:
            asset = self.assets_by_id[str(music_id)]
            self._indent(indent, f'play music "audio/{asset.filename}" fadein 0 loop')
        title = data.get("title")
        if title:
            self._indent(indent, f'"{_escape_renpy_string(str(title))}"')
        intro_text = data.get("intro_text")
        if intro_text:
            character = _sanitize_renpy_name(str(data.get("intro_character", "narrator")))
            if character == "narrator":
                self._indent(indent, f'"{_escape_renpy_string(str(intro_text))}"')
            else:
                self._indent(indent, f'{character} "{_escape_renpy_string(str(intro_text))}"')

    def _emit_scene(self, node: GraphNode, indent: int) -> None:
        data = node.data or {}
        image_name = self._asset_image_name(data.get("asset_id"))
        transition = data.get("transition", "dissolve")
        if image_name:
            self._indent(indent, f"scene {image_name} with {transition}")
        else:
            self._indent(indent, f"scene black with {transition}")

    def _emit_dialogue(self, node: GraphNode, indent: int) -> None:
        data = node.data or {}
        text = _escape_renpy_string(data.get("text", ""))
        character = _sanitize_renpy_name(data.get("character", "narrator"))
        if character == "narrator":
            self._indent(indent, f'"{text}"')
        else:
            self._indent(indent, f'{character} "{text}"')

    def _emit_show_character(self, node: GraphNode, indent: int) -> None:
        data = node.data or {}
        image_name = self._asset_image_name(data.get("asset_id"))
        char_id = _sanitize_renpy_name(data.get("character_id", "character"))
        position = POSITION_MAP.get(data.get("position", "center"), "center")
        if image_name:
            self._indent(indent, f"show {image_name} as {char_id} at {position}")

    def _emit_hide_character(self, node: GraphNode, indent: int) -> None:
        char_id = _sanitize_renpy_name((node.data or {}).get("character_id", "character"))
        self._indent(indent, f"hide {char_id}")

    def _emit_music(self, node: GraphNode, indent: int) -> None:
        data = node.data or {}
        asset_id = data.get("asset_id")
        if not asset_id or asset_id not in self.assets_by_id:
            return
        asset = self.assets_by_id[asset_id]
        fade = data.get("fade", 0)
        loop = "loop" if data.get("loop", True) else "noloop"
        self._indent(indent, f'play music "audio/{asset.filename}" fadein {fade} {loop}')

    def _emit_sound(self, node: GraphNode, indent: int) -> None:
        data = node.data or {}
        asset_id = data.get("asset_id")
        if not asset_id or asset_id not in self.assets_by_id:
            return
        asset = self.assets_by_id[asset_id]
        self._indent(indent, f'play sound "audio/{asset.filename}"')

    def _emit_effect(self, node: GraphNode, indent: int) -> None:
        data = node.data or {}
        effect_type = data.get("effect_type", "dissolve")
        if effect_type == "fade":
            duration = data.get("params", {}).get("duration", 1.0)
            self._indent(indent, f"with Fade({duration}, 0.0, 0.0)")
        elif effect_type == "dissolve":
            self._indent(indent, "with dissolve")
        elif effect_type == "shake":
            self._indent(indent, "camera shake")

    def _emit_set_variable(self, node: GraphNode, indent: int) -> None:
        data = node.data or {}
        name = _sanitize_renpy_name(data.get("name", "var"))
        value = data.get("value", 0)
        if isinstance(value, str):
            self._indent(indent, f'$ {name} = "{_escape_renpy_string(value)}"')
        else:
            self._indent(indent, f"$ {name} = {value}")

    def _emit_jump(self, node: GraphNode, indent: int) -> None:
        target = _sanitize_renpy_name((node.data or {}).get("target_label", ""))
        if target:
            self._indent(indent, f"jump {target}")

    def _emit_choice(self, node: GraphNode, indent: int) -> None:
        data = node.data or {}
        options = data.get("options", [])
        outgoing = self.adj.get(node.id, [])
        handle_to_target = {e.source_handle: e.target_node_id for e in outgoing}

        self._indent(indent, "menu:")
        for i, option in enumerate(options):
            handle = option.get("handle") or f"option_{i}"
            text = _escape_renpy_string(option.get("text", f"Option {i + 1}"))
            self._indent(indent + 1, f'"{text}":')
            target_id = handle_to_target.get(handle)
            if target_id:
                branch_label = f"{_sanitize_renpy_name(node.label)}_{handle}"
                self._indent(indent + 2, f"jump {branch_label}")
                self.lines.append("")
                self.lines.append(f"label {branch_label}:")
                self._emit_from_node(target_id, indent=1, stop_at_branch=True)

    def _emit_condition(self, node: GraphNode, indent: int) -> None:
        data = node.data or {}
        expression = data.get("expression", "True")
        outgoing = self.adj.get(node.id, [])
        handle_to_target = {e.source_handle: e.target_node_id for e in outgoing}

        true_id = handle_to_target.get("true")
        false_id = handle_to_target.get("false")

        self._indent(indent, f"if {expression}:")
        if true_id:
            self._emit_from_node(true_id, indent + 1, stop_at_branch=True)
        else:
            self._indent(indent + 1, "pass")

        if false_id:
            self._indent(indent, "else:")
            self._emit_from_node(false_id, indent + 1, stop_at_branch=True)


def _pos_align(pos: dict | None, default_x: float = 0.5, default_y: float = 0.5) -> tuple[float, float]:
    x = float(pos.get("x", default_x * 100) if pos else default_x * 100) / 100.0
    y = float(pos.get("y", default_y * 100) if pos else default_y * 100) / 100.0
    return x, y


def _generate_screens_rpy(project: Project) -> str:
    metadata = project.metadata_ or {}
    screens = metadata.get("game_screens") or {}
    loading = screens.get("loading") or {}
    main_menu = screens.get("main_menu") or {}
    settings = screens.get("settings") or {}

    loading_title = _escape_renpy_string(str(loading.get("title") or project.title))
    loading_subtitle = _escape_renpy_string(str(loading.get("subtitle") or "Загрузка..."))
    loading_tip = _escape_renpy_string(str(loading.get("tip_text") or ""))
    menu_title = _escape_renpy_string(str(main_menu.get("title") or project.title))
    settings_title = _escape_renpy_string(str(settings.get("title") or "Настройки"))

    lt_x, lt_y = _pos_align(loading.get("title_pos"), 0.5, 0.38)
    ls_x, ls_y = _pos_align(loading.get("subtitle_pos"), 0.5, 0.52)
    ltip_x, ltip_y = _pos_align(loading.get("tip_pos"), 0.5, 0.88)
    mt_x, mt_y = _pos_align(main_menu.get("title_pos"), 0.5, 0.22)
    st_x, st_y = _pos_align(settings.get("title_pos"), 0.5, 0.22)

    menu_items = main_menu.get("items") or []
    menu_lines = []
    for item in menu_items:
        label = _escape_renpy_string(str(item.get("label", "Пункт")))
        action = str(item.get("action", "start"))
        ix, iy = _pos_align(item, 0.5, 0.5)
        action_line = 'Start()'
        if action == "settings":
            action_line = 'ShowMenu("preferences")'
        elif action == "load":
            action_line = 'ShowMenu("load")'
        elif action == "quit":
            action_line = "Quit(confirm=not main_menu)"
        menu_lines.append(
            f'    textbutton "{label}" action {action_line} xalign {ix:.3f} yalign {iy:.3f}'
        )

    settings_items = settings.get("items") or []
    pref_lines = []
    for item in settings_items:
        label = _escape_renpy_string(str(item.get("label", "Настройка")))
        item_type = str(item.get("type", "toggle"))
        ix, iy = _pos_align(item, 0.5, 0.5)
        if item_type == "slider":
            pref_lines.append(
                f'    vbox:\n        xalign {ix:.3f}\n        yalign {iy:.3f}\n        label "{label}"\n        bar value Preference("text speed")'
            )
        elif item_type == "button":
            pref_lines.append(
                f'    textbutton "{label}" action NullAction() xalign {ix:.3f} yalign {iy:.3f}'
            )
        else:
            pref_lines.append(
                f'    textbutton "{label}" action Preference("all mute", "toggle") xalign {ix:.3f} yalign {iy:.3f}'
            )

    menu_body = "\n".join(menu_lines) or '    textbutton "Начать игру" action Start() xalign 0.5 yalign 0.5'
    pref_body = "\n".join(pref_lines) or '    textbutton "Назад" action Return()'

    return f'''## Generated screens — loading, main menu, settings

screen loading_screen():
    tag loading
    add Solid("#000000")
    text "{loading_title}" size 48 xalign {lt_x:.3f} yalign {lt_y:.3f}
    text "{loading_subtitle}" size 24 xalign {ls_x:.3f} yalign {ls_y:.3f}
    if "{loading_tip}":
        text "{loading_tip}" size 18 color "#888888" xalign {ltip_x:.3f} yalign {ltip_y:.3f}

screen main_menu():
    tag menu
    add Solid("#111111")
    text "{menu_title}" size 52 xalign {mt_x:.3f} yalign {mt_y:.3f}
{menu_body}

screen game_settings():
    tag menu
    use game_menu(_("{settings_title}")):
        text "{settings_title}" size 40 xalign {st_x:.3f} yalign {st_y:.3f}
{pref_body}
        textbutton "Назад" action Return()
'''


async def build_renpy_zip(project: Project) -> bytes:
    errors = validate_graph(project)
    if errors:
        raise ValueError("\n".join(errors))

    generator = RenPyGenerator(project)
    script = generator.generate_script()
    storage = get_storage()

    buffer = io.BytesIO()
    safe_title = _sanitize_renpy_name(project.title) or "game"
    metadata = project.metadata_ or {}
    screen_width = int(metadata.get("screen_width", 1280))
    screen_height = int(metadata.get("screen_height", 720))

    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr(
            f"{safe_title}/game/options.rpy",
            f'define config.name = "{_escape_renpy_string(project.title)}"\n'
            f'define config.version = "1.0"\n'
            f"define config.screen_width = {screen_width}\n"
            f"define config.screen_height = {screen_height}\n",
        )
        zf.writestr(f"{safe_title}/game/script.rpy", script)
        zf.writestr(f"{safe_title}/game/screens_custom.rpy", _generate_screens_rpy(project))
        zf.writestr(
            f"{safe_title}/project.json",
            json.dumps({"title": project.title, "id": str(project.id)}, ensure_ascii=False, indent=2),
        )

        for asset in project.assets:
            data = await storage.download(asset.storage_key)
            if asset.kind == "background":
                path = f"{safe_title}/game/images/bg/{asset.filename}"
            elif asset.kind == "character":
                path = f"{safe_title}/game/images/char/{asset.filename}"
            else:
                path = f"{safe_title}/game/audio/{asset.filename}"
            zf.writestr(path, data)

    return buffer.getvalue()
